name: (Dev) Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract short SHA
        id: meta
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to GHCR
        run: |
          IMAGE_URL=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          docker build \
          -t $IMAGE_URL:beta-${{ steps.meta.outputs.sha }} \
          -t $IMAGE_URL:beta-latest .

          docker push $IMAGE_URL:beta-${{ steps.meta.outputs.sha }}
          docker push $IMAGE_URL:beta-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      HUSKY: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH to DigitalOcean
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            IMAGE_URL=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}
            docker stop ${{ github.event.repository.name }}-beta || true
            docker rm ${{ github.event.repository.name }}-beta || true
            docker image prune -a -f
            docker run -d --name ${{ github.event.repository.name }}-beta -p 3001:3000 \
            $IMAGE_URL:beta-latest
